### PR TITLE
remove SVG icon title

### PR DESCRIPTION
**Pull request by embbnux**
remove SVG icon title
fix docs page build fail

### CODE REVIEW

**Comment by u9520107** [comment]
Is there a particular reason why those should be removed?
If it is important, how can we ensure that other projects using these will remember to the correct webpack configuration?

**Comment by embbnux** [comment]
In some SVG icon file, it provides some meaningless title. when user hover on SVG icon, it will show those title.
Maybe, we can provider webpack base config. But I think it is better to provide SVG file with correct info.

**Comment by u9520107** [comment]
Perhaps it is better to just remove the title and description tag from those svg files?

**Comment by embbnux** [comment]
@u9520107 yeah, I can remove them.

**Pull request merged**
